[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# Remappings for Hyperlane
remappings = [
    "@hyperlane-xyz/core/=lib/hyperlane-monorepo/solidity/contracts/",
    "@hyperlane-xyz/core/interfaces/=lib/hyperlane-monorepo/solidity/contracts/interfaces/",
    "@hyperlane-xyz/core/libs/=lib/hyperlane-monorepo/solidity/contracts/libs/",
    "@hyperlane-xyz/core/contracts/=lib/hyperlane-monorepo/solidity/contracts/",
    "@openzeppelin/contracts/=lib/hyperlane-monorepo/solidity/contracts/libs/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/hyperlane-monorepo/solidity/contracts/libs/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@solmate/=lib/hyperlane-monorepo/solidity/contracts/libs/solmate/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
